baseURL = "https://loommii.github.io/"
languageCode = "zh"
defaultContentLanguage = "zh"
title = "loommii"
theme = [ "PaperMod" ]

[params]
comments = true
ShowBreadCrumbs = true

[params.profileMode]
enabled = true
title = "loommii"
subtitle = "好记性不如烂笔头💡🖋️📚"
imageUrl = "img/author.png"
imageWidth = 120
imageHeight = 120

[[params.socialIcons]]
name = "github"
url = "https://github.com/loommii"

[[params.socialIcons]]
name = "email"
url = "v1061827272@hotmail.com"

[params.assets]
favicon = "/favicon.ico"
favicon16x16 = "/favicon-16x16.png"
favicon32x32 = "/favicon-32x32.png"
apple_touch_icon = "/apple-touch-icon.png"
safari_pinned_tab = "/safari-pinned-tab.svg"

ignoreLogs = ['error-partial-not-found']

[outputs]
home = [ "HTML", "RSS", "JSON" ]