baseURL = "https://loommii.github.io/"
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"
title = "loommii"
theme = "hugo-theme-stack"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = true

[params]
mainSections = ["posts"]
featuredImageField = "image"
rssFullContent = true
favicon = ""

[params.sidebar]
emoji = "🎯"
subtitle = "好记性不如烂笔头💡🖋️📚"
[params.sidebar.avatar]
enabled = true
local = true
src = "img/author.png"

[params.article]
math = false
toc = true
readingTime = true
[params.article.license]
enabled = true
default = "Licensed under CC BY-NC-SA 4.0"

[params.comments]
enabled = true
provider = "disqus"

[params.footer]
since = 2024
customText = ""

[params.dateFormat]
published = "Jan 02, 2006"
lastUpdated = "Jan 02, 2006 15:04 MST"

[params.opengraph]
[params.opengraph.twitter]
site = ""
card = "summary_large_image"

[params.colorScheme]
toggle = true
default = "auto"

[params.imageProcessing]
[params.imageProcessing.cover]
enabled = true
[params.imageProcessing.content]
enabled = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "文章"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 2

  [[menu.main]]
    identifier = "categories"
    name = "分类"
    url = "/categories/"
    weight = 3

  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 4

  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 5

  [[menu.social]]
    name = "GitHub"
    url = "https://github.com/loommii"
    weight = 1
    [menu.social.params]
      icon = "brand-github"

  [[menu.social]]
    name = "Email"
    url = "mailto:v1061827272@hotmail.com"
    weight = 2

[related]
includeNewer = true
threshold = 60
toLower = false
[[related.indices]]
name = "tags"
weight = 100
[[related.indices]]
name = "categories"
weight = 200

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      passthrough = { enable = true }
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[outputs]
home = ["HTML", "RSS"]
page = ["HTML"]
section = ["HTML", "RSS"]