[[main]]
  name = "文章"
  pageRef = "/posts/skill"
  weight = 5
  
[[main]]
  name = "Golang练习"
  pageRef = "/posts/go_practise"
  weight = 10

[[main]]
  name = "力扣"
  pageRef = "/posts/leetcode"
  weight = 20

[[main]]
  name = "归档"
  pageRef = "/archives"
  weight = 30

[[main]]
  name = "搜索"
  pageRef = "/search"
  weight = 40